metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: false

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

metricbeat.modules:
- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "healthcheck"
    - "info"
    #- "image"
    - "memory"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true

- module: elasticsearch
  metricsets: ["node", "node_stats"]
  period: 10s
  hosts: ["elasticsearch:9200"]  

- module: mysql
  metricsets: ["status"]
  hosts: ["tcp(db:3306)/"]
  username: admin
  password: correia97*

- module: nginx
  metricsets: ["stubstatus"]
  enabled: true
  period: 10s

  # Nginx hosts
  hosts: ["http://nginx"]

  # Path to server status. Default nginx_status
  server_status_path: "nginx_status"




# - module: rabbitmq
#   metricsets: ["node", "queue"]
#   period: 10s
#   hosts: ["rabbitmq:15672"]
#   username: logUser
#   password: logPwd  


processors:
  - add_cloud_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'

setup.kibana:
  host: "kibana:5601"
  
setup.dashboards.enabled: true
