apiVersion: apps/v1
kind: Deployment
metadata:
  name: es03
spec:
  selector:
    matchLabels:
      app: es03
  template:
    metadata:
      labels:
        app: es03
        network/elastic: "true"
    spec:
      initContainers:
        - name: sysctl
          image: busybox:1.28
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
      containers:
      - name: es03     
        securityContext:
          privileged: true
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: http2
        - containerPort: 9600
          name: http3
        env:
          - name: node.name
            value: es03
          - name: cluster.name
            value: es-docker-cluster
          - name: discovery.seed_hosts
            value: service-es01,service-es02
          - name: cluster.initial_master_nodes
            value: es01,es02,es03
          - name: bootstrap.memory_lock
            value: "false"
          - name: "ES_JAVA_OPTS"
            value: "-Xms512m -Xmx512m"    
