apiVersion: v1
kind: Service
metadata:
  name: service-es01
spec:
  selector:
    app: es01
  ports:
  - port: 9200  
    name: http
    targetPort: 9200
  - port: 9300
    name: http2
    targetPort: 9300
  - port: 9600
    name: http3
    targetPort: 9600
