apiVersion: v1
kind: Service
metadata:
  name: nodeport-service-kibana
spec:
  selector:
    app: kibana
  ports:
  - port: 5601
    targetPort: 5601
    name: http
  type: NodePort  
---
apiVersion: v1
kind: Service
metadata:
  name: service-kibana
spec:
  selector:
    app: kibana
  ports:
  - port: 5601
    targetPort: 5601
    name: http 